-- Generated by kestrel_gen. The operational slice: the last 90 business days.
-- Money is BIGINT minor units and FX is DECIMAL(18,8); no float (D1).

DROP TABLE IF EXISTS cities CASCADE;
CREATE TABLE cities (
  city_id TEXT,
  region_id TEXT,
  name TEXT
);

DROP TABLE IF EXISTS countries CASCADE;
CREATE TABLE countries (
  country_code TEXT,
  name TEXT,
  currency TEXT,
  timezone TEXT
);

DROP TABLE IF EXISTS customers CASCADE;
CREATE TABLE customers (
  customer_id TEXT,
  phone_masked TEXT,
  email_hash TEXT
);

DROP TABLE IF EXISTS order_items CASCADE;
CREATE TABLE order_items (
  order_id TEXT,
  line_no SMALLINT,
  sku TEXT,
  qty SMALLINT,
  unit_price_minor BIGINT
);

DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  order_id TEXT,
  showroom_id TEXT,
  channel TEXT,
  created_at_utc TIMESTAMP,
  business_date DATE,
  currency TEXT,
  total_minor BIGINT,
  status TEXT,
  is_test BOOLEAN,
  customer_id TEXT
);

DROP TABLE IF EXISTS payment_attempts CASCADE;
CREATE TABLE payment_attempts (
  attempt_id TEXT,
  order_id TEXT,
  attempt_no SMALLINT,
  method TEXT,
  card_network TEXT,
  issuing_bank TEXT,
  acquiring_bank TEXT,
  emi_tenure_months TEXT,
  amount_minor BIGINT,
  currency TEXT,
  status TEXT,
  failure_reason TEXT,
  created_at_utc TIMESTAMP,
  business_date DATE,
  gateway_payment_id TEXT,
  is_test BOOLEAN
);

DROP TABLE IF EXISTS prices CASCADE;
CREATE TABLE prices (
  sku TEXT,
  country_code TEXT,
  price_minor BIGINT,
  valid_from TEXT,
  valid_to TEXT
);

DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
  sku TEXT,
  model_id TEXT,
  model_name TEXT,
  storage_gb BIGINT,
  colour TEXT,
  launch_date TEXT,
  is_accessory BOOLEAN
);

DROP TABLE IF EXISTS refunds CASCADE;
CREATE TABLE refunds (
  refund_id TEXT,
  order_id TEXT,
  attempt_id TEXT,
  amount_minor BIGINT,
  currency TEXT,
  reason TEXT,
  status TEXT,
  created_at_utc TIMESTAMP,
  business_date DATE,
  processed_on DATE
);

DROP TABLE IF EXISTS regions CASCADE;
CREATE TABLE regions (
  region_id TEXT,
  country_code TEXT,
  name TEXT
);

DROP TABLE IF EXISTS showrooms CASCADE;
CREATE TABLE showrooms (
  showroom_id TEXT,
  city_id TEXT,
  name TEXT,
  opened_on TEXT,
  region_id TEXT,
  country_code TEXT
);
