"""receipts.mcp_server.tools — the tools themselves, with the role passed in.

Separated from the transport on purpose. The MCP server is a second front door
onto the same engine, and the risk a second front door carries is that it grows
a second implementation: a slightly different validate, a scope derived from a
slightly different place, a plan hash that no longer matches the web's. J6 exists
to catch exactly that.

So `ask` here calls the same `orchestrator.answer` the API route calls, and
`run_plan` walks the same validate → gate → compile → guard → execute path. There
is no MCP-specific engine code below this line, which is what makes the parity
test a statement about the architecture rather than about two functions that
currently agree.

**Scope comes from the role and never from the tool's arguments.** `run_plan`
takes a `QueryPlan`, and a `QueryPlan` has no scope field (D7) -- so a caller
cannot express one, which is stronger than rejecting one. F8 asserts that a plan
crafted to reach outside the role is denied rather than filtered quietly.
"""

from __future__ import annotations

from typing import Any

from ..agent.orchestrator import answer as run_answer
from ..agent.session import Session
from ..agent.validate import Issues, validate
from ..api.deps import Runtime
from ..compile.compiler import compile_query
from ..domain.types import Grain, Intent, QueryPlan, Status, WindowSpec
from ..observability.audit import AuditEvent
from ..safety.guard import allowlist_for_role, guard

# Tools every role gets. Gateway tools are generated by the bridge (SDD §20) and
# are cut with M19; the CAPABILITY FILTER that hides them is built and tested
# anyway, because it is the part that has to be right before they exist.
BASE_TOOLS: tuple[str, ...] = (
    "list_metrics",
    "describe_metric",
    "ask",
    "run_plan",
    "explain_answer",
)

GATEWAY_CAPABILITY = "gateway"


def tools_for(role: str, runtime: Runtime, gateway_tools: tuple[str, ...] = ()) -> tuple[str, ...]:
    """The tool names this role may see.

    A role without `gateway` is not told the gateway tools exist -- they are
    absent from the listing rather than present and refused. The same reasoning
    as the planner's metric enum: a refusal discloses that there was something
    to refuse.
    """
    scope = runtime.scope(role)
    if GATEWAY_CAPABILITY in scope.capabilities:
        return BASE_TOOLS + gateway_tools
    return BASE_TOOLS


def list_metrics(runtime: Runtime, role: str) -> dict[str, Any]:
    held = set(runtime.scope(role).capabilities)
    return {
        "metrics": [
            {"name": m.name, "label": m.label.get("en", m.name), "definition": m.definition}
            for m in runtime.deps.catalog.metrics
            if m.required_capability is None or m.required_capability in held
        ]
    }


def describe_metric(runtime: Runtime, role: str, name: str) -> dict[str, Any]:
    held = set(runtime.scope(role).capabilities)
    for metric in runtime.deps.catalog.metrics:
        if metric.name != name:
            continue
        if metric.required_capability and metric.required_capability not in held:
            break  # Not "forbidden": that would disclose it exists.
        return {
            "name": metric.name,
            "label": metric.label,
            "definition": metric.definition,
            "glossary_ref": metric.glossary_ref,
            "unit": metric.unit,
            "allowed_dimensions": list(metric.allowed_dimensions),
            "siblings": list(metric.siblings),
            "excludes": list(metric.excludes),
        }
    return {"error": "no such metric", "name": name}


def ask(runtime: Runtime, role: str, question: str, session_id: str = "mcp") -> dict[str, Any]:
    """The same call the web route makes. J6 depends on this being literal."""
    budget = getattr(runtime.deps.llm, "budget", None)
    if budget is not None:
        budget.reset()
    scope = runtime.scope(role)
    result, _trace = run_answer(
        question,
        Session(session_id=session_id, role=role),
        scope,
        runtime.as_of,
        runtime.deps,
    )
    receipt = result.receipt
    runtime.audit.append(
        AuditEvent(
            role=role,
            session_id=session_id,
            question_text=question,
            lang=result.language.value if result.language else "en",
            status=result.status.value,
            receipt_id=receipt.receipt_id if receipt else None,
            plan_hash=receipt.plan_hash if receipt else None,
            sql_hash=receipt.sql_hash if receipt else None,
            row_count=len(result.table.rows) if result.table else None,
            reason=result.reason or "",
        )
    )
    return {
        "status": result.status.value,
        "narration": result.narration,
        "rows": [[str(cell) for cell in row] for row in result.table.rows] if result.table else [],
        "columns": [c.name for c in result.table.columns] if result.table else [],
        "receipt_id": receipt.receipt_id if receipt else None,
        "plan_hash": receipt.plan_hash if receipt else None,
        "sql_hash": receipt.sql_hash if receipt else None,
        "reason": result.reason,
    }


def run_plan(runtime: Runtime, role: str, plan_body: dict[str, Any]) -> dict[str, Any]:
    """A caller-supplied plan, through the web path's own stages (F8).

    The scope is fetched from the role here and the plan cannot carry one. A plan
    naming a country outside the role's regions reaches gate rule 1 and is
    DENIED by name; a plan naming nothing at all is scoped by the compiler's
    predicate and comes back with the role's regions only.
    """
    scope = runtime.scope(role)
    plan = _plan_from(plan_body)

    validated = validate(
        plan,
        runtime.deps.catalog,
        scope,
        runtime.as_of,
        question="",
        prefs={},
        first_date=runtime.deps.first_date,
        last_date=runtime.deps.last_date,
    )

    from ..agent.gate import gate

    decision = gate(
        question="",
        intent=_metric_intent(),
        validated=validated,
        plan=plan,
        scope=scope,
        catalog=runtime.deps.catalog,
        places=runtime.places,
        freeform_enabled=False,
    )
    if decision.decision != "PROCEED":
        _audit(runtime, role, plan, decision.decision, decision.reason)
        return {
            "status": "DENIED" if decision.decision == "DENY" else decision.decision,
            "rule": decision.rule,
            "reason": decision.reason,
        }
    assert not isinstance(validated, Issues)

    compiled = compile_query(
        validated.resolved,
        runtime.deps.catalog,
        scope,
        runtime.deps.adapter.dialect,
        row_limit=runtime.deps.row_limit,
    )
    allowlist = allowlist_for_role(role, runtime.deps.catalog, runtime.deps.roles)
    checked = guard(
        compiled.sql, runtime.deps.adapter.dialect, allowlist, row_limit=runtime.deps.row_limit
    )
    if not checked.ok:
        _audit(runtime, role, plan, "GUARD_REJECTED", checked.reason)
        return {"status": "GUARD_REJECTED", "reason": checked.reason}

    metric = runtime.deps.catalog.metric(plan.name)
    table = runtime.deps.adapter.run(
        compiled,
        row_limit=runtime.deps.row_limit,
        timeout_s=runtime.deps.timeout_s,
        money=metric.money,
        currency=validated.resolved.reporting_currency,
    )
    _audit(
        runtime,
        role,
        plan,
        Status.VERIFIED.value,
        "",
        plan_hash=validated.resolved.plan_hash,
        sql_hash=compiled.sql_hash,
        rows=len(table.rows),
    )
    return {
        "status": Status.VERIFIED.value,
        "columns": [c.name for c in table.columns],
        "rows": [[str(cell) for cell in row] for row in table.rows],
        "plan_hash": validated.resolved.plan_hash,
        "sql_hash": compiled.sql_hash,
        "reporting_currency": validated.resolved.reporting_currency,
    }


def explain_answer(runtime: Runtime, role: str, receipt_id: str) -> dict[str, Any]:
    row = runtime.audit.by_receipt(receipt_id)
    if row is None:
        return {"error": "no such receipt", "receipt_id": receipt_id}
    if row["role"] != role and "audit" not in runtime.scope(role).capabilities:
        return {"error": "that receipt belongs to another role"}
    return {"audit": row}


# --------------------------------------------------------------------------- #


def _plan_from(body: dict[str, Any]) -> QueryPlan:
    from ..domain.types import Filter

    window = body.get("window") or {"kind": "relative", "relative": "last_month"}
    return QueryPlan(
        kind="metric",
        name=str(body.get("metric") or body.get("name") or ""),
        dimensions=tuple(body.get("dimensions") or ()),
        filters=tuple(
            Filter(
                dimension=str(f["dimension"]),
                op=str(f.get("op", "eq")),  # type: ignore[arg-type]
                values=tuple(f["values"]),
            )
            for f in (body.get("filters") or ())
        ),
        window=WindowSpec(**window),
        grain=Grain(str(body.get("grain", "NONE"))),
        limit=body.get("limit"),
        order=body.get("order"),
    )


def _metric_intent() -> Any:
    return Intent.METRIC


def _audit(
    runtime: Runtime,
    role: str,
    plan: QueryPlan,
    status: str,
    reason: str,
    *,
    plan_hash: str | None = None,
    sql_hash: str | None = None,
    rows: int | None = None,
) -> None:
    runtime.audit.append(
        AuditEvent(
            role=role,
            session_id="mcp",
            question_text=f"run_plan:{plan.name}",
            lang="en",
            status=status,
            plan_hash=plan_hash,
            sql_hash=sql_hash,
            row_count=rows,
            reason=reason,
        )
    )


__all__ = [
    "BASE_TOOLS",
    "GATEWAY_CAPABILITY",
    "ask",
    "describe_metric",
    "explain_answer",
    "list_metrics",
    "run_plan",
    "tools_for",
]
