"""What each question computes, written from the question text.

The honest part of `scripts/double_compute.py` is that this table is **not**
independent of the reference SQL: the same author read the same question and the
same glossary twice. A misreading of the question survives both.

What the double computation does catch is everything below the reading: a join
that fans out, a window boundary typed wrongly, a `group by` that drops nulls, a
duplicate not deduplicated, an FX rate taken on the wrong date, a float where a
Decimal belonged. Those are the mistakes that actually happen at this volume.

So this file is deliberately declarative and short per entry — metric, window
token, scope, breakdown, currency — and carries no computation at all. The
computation lives in `double_compute.py` and is written in pandas against the
Parquet files, sharing nothing with the SQL.

Keys:
  metric          a name in double_compute.METRICS
  window          a token resolved by double_compute.window() from as_of
  scope           equality filters on the order's geography or channel
  breakdown       None | a dimension name | "daily" | "weekly" | "compare"
                  | "compare:<dimension>"
  breakdown_via   "handset" for §1.7a money attribution, "line" for §2.2 units
  currency        the reporting currency, for money and for ratios that convert
  plus per-metric narrowing: method, issuing_bank, status, reason, ...
"""

from __future__ import annotations

from typing import Any

TN = {"region_id": "IN-TN"}
CHENNAI = {"city_name": "Chennai"}

SPEC: dict[str, dict[str, Any]] = {
    # ---------------------------------------------------------------- dev ----
    "DV-001": {
        "metric": "success_rate_order",
        "window": "yesterday",
        "scope": CHENNAI,
        "method": "upi",
    },
    "DV-002": {"metric": "orders_count", "window": "yesterday", "scope": TN},
    "DV-003": {"metric": "captured_gmv", "window": "last_month", "currency": "USD"},
    "DV-004": {
        "metric": "captured_gmv",
        "window": "last_week",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
    },
    "DV-005": {"metric": "settlement_lag", "window": "august_2026"},
    "DV-006": {
        "metric": "refund_rate",
        "window": "this_month_to_date",
        "currency": "INR",
        "scope": TN,
    },
    "DV-007": {
        "metric": "units_sold",
        "window": "last_month",
        "scope": {"country_code": "GB"},
        "breakdown": "showroom_name",
    },
    "DV-008": {
        "metric": "emi_share",
        "window": "last_month",
        "currency": "INR",
        "scope": {"country_code": "IN"},
    },
    "DV-009": {
        "metric": "failure_rate_by_reason",
        "window": "last_7_days",
        "scope": CHENNAI,
        "breakdown": "failure_reason",
    },
    "DV-010": {
        "metric": "success_rate_order",
        "window": "last_month",
        "scope": {"country_code": "GB"},
        "method": "card",
        "breakdown": "issuing_bank",
    },
    "DV-011": {
        "metric": "attempts_per_order",
        "window": "all_loaded",
        "scope": {"country_code": "IN"},
    },
    "DV-012": {
        "metric": "status_share",
        "window": "last_month",
        "scope": CHENNAI,
        "status": "cancelled",
    },
    "DV-020": {
        "metric": "pending_refund_value",
        "window": "last_week",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
        "breakdown": "refund_id",
    },
    "DV-021": {"metric": "net_revenue", "window": "august_2026", "currency": "USD"},
    "DV-022": {"metric": "duplicate_capture_count", "window": "last_month", "scope": TN},
    "DV-023": {"metric": "attempts_count", "window": "last_month", "scope": {"country_code": "SG"}},
    "DV-024": {
        "metric": "average_order_value",
        "window": "last_month",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
    },
    "DV-025": {
        "metric": "emi_share",
        "window": "last_month",
        "currency": "INR",
        "scope": TN,
        "breakdown": "city_name",
    },
    "DV-026": {"metric": "unsettled_amount", "window": "august_2026", "currency": "USD"},
    "DV-027": {"metric": "orders_count", "window": "yesterday", "scope": {"country_code": "GB"}},
    "DV-028": {
        "metric": "success_rate_attempt",
        "window": "last_week",
        "scope": CHENNAI,
        "method": "upi",
    },
    "DV-029": {
        "metric": "units_sold",
        "window": "last_month",
        "handsets_only": True,
        "breakdown": "model_name",
        "breakdown_via": "line",
    },
    "DV-030": {
        "metric": "refunded_amount",
        "window": "last_month",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
    },
    "DV-031": {
        "metric": "attach_rate",
        "window": "last_month",
        "scope": CHENNAI,
        "breakdown": "showroom_name",
    },
    "DV-032": {"metric": "authorised_not_captured", "window": "august_2026", "currency": "USD"},
    "DV-033": {
        "metric": "distinct_issuing_banks",
        "window": "last_month",
        "scope": {"country_code": "GB"},
    },
    "DV-041": {
        "metric": "captured_gmv",
        "window": "this_month_to_date",
        "currency": "INR",
        "scope": TN,
        "breakdown": "compare",
    },
    "DV-042": {
        "metric": "captured_gmv",
        "window": "last_month",
        "currency": "USD",
        "breakdown": "compare:country_code",
    },
    "DV-043": {
        "metric": "success_rate_order",
        "window": "last_week",
        "scope": {"country_code": "GB"},
        "breakdown": "compare",
    },
    "DV-044": {
        "metric": "orders_count",
        "window": "last_7_days",
        "scope": TN,
        "breakdown": "daily",
    },
    "DV-045": {
        "metric": "captured_gmv",
        "window": "last_8_weeks",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
        "breakdown": "weekly",
    },
    "DV-046": {
        "metric": "settlement_lag",
        "window": "august_2026",
        "method": "emi",
        "breakdown": "settlement_bank",
    },
    "DV-047": {
        "metric": "refund_rate",
        "window": "last_month",
        "currency": "USD",
        "scope": {"country_code": "AE"},
        "method": "card",
        "breakdown": "model_name",
        "breakdown_via": "handset",
    },
    "DV-048": {
        "metric": "success_rate_order",
        "window": "last_month",
        "scope": CHENNAI,
        "method": "upi",
        "breakdown": "issuing_bank",
    },
    "DV-049": {
        "metric": "attempts_count",
        "window": "last_week",
        "scope": {"country_code": "GB"},
        "method": "card",
        "status": "failed",
    },
    "DV-050": {
        "metric": "net_revenue",
        "window": "last_month",
        "currency": "MYR",
        "scope": {"country_code": "MY"},
    },
    "DV-051": {
        "metric": "median_order_value",
        "window": "last_month",
        "currency": "SGD",
        "scope": {"country_code": "SG"},
    },
    "DV-060": {
        "metric": "pending_refund_value",
        "window": "last_week",
        "currency": "INR",
        "scope": CHENNAI,
        "breakdown": "refund_id",
    },
    # --------------------------------------------------------------- eval ----
    "EV-001": {
        "metric": "captured_gmv",
        "window": "july_2026",
        "currency": "USD",
        "breakdown": "country_code",
    },
    "EV-002": {
        "metric": "captured_gmv",
        "window": "july_2026",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
        "breakdown": "channel",
    },
    "EV-003": {
        "metric": "captured_gmv",
        "window": "yesterday",
        "currency": "INR",
        "scope": TN,
        "breakdown": "city_name",
    },
    "EV-004": {
        "metric": "success_rate_order",
        "window": "last_week",
        "scope": {"country_code": "SG"},
    },
    "EV-005": {
        "metric": "refund_rate",
        "window": "august_2026",
        "currency": "USD",
        "breakdown": "country_code",
    },
    "EV-006": {
        "metric": "average_order_value",
        "window": "july_2026",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
        "breakdown": "city_name",
    },
    "EV-007": {"metric": "emi_share", "window": "july_2026", "currency": "INR", "scope": TN},
    "EV-008": {"metric": "settlement_lag", "window": "july_2026", "breakdown": "settlement_bank"},
    "EV-009": {"metric": "orders_count", "window": "july_2026", "scope": {"country_code": "MY"}},
    "EV-010": {
        "metric": "success_rate_order",
        "window": "last_week",
        "scope": {"country_code": "GB"},
        "method": "card",
        "breakdown": "card_network",
    },
    "EV-011": {
        "metric": "units_sold",
        "window": "last_month",
        "scope": TN,
        "breakdown": "city_name",
    },
    "EV-012": {
        "metric": "duplicate_capture_value",
        "window": "august_2026",
        "currency": "INR",
        "scope": {"country_code": "IN"},
    },
    "EV-013": {
        "metric": "net_revenue",
        "window": "this_month_to_date",
        "currency": "USD",
        "breakdown": "compare",
    },
    "EV-014": {
        "metric": "units_sold",
        "window": "last_week",
        "scope": {"country_code": "GB"},
        "breakdown": "compare",
    },
    "EV-015": {
        "metric": "captured_gmv",
        "window": "last_7_days",
        "currency": "INR",
        "scope": CHENNAI,
        "breakdown": "daily",
    },
    "EV-016": {"metric": "attach_rate", "window": "july_2026", "breakdown": "country_code"},
    "EV-017": {
        "metric": "settlement_lag",
        "window": "july_2026",
        "scope": {"country_code": "MY"},
        "method": "emi",
        "breakdown": "settlement_bank",
    },
    "EV-018": {"metric": "refund_rate", "window": "last_week", "currency": "INR", "scope": TN},
    "EV-019": {
        "metric": "failure_rate_by_reason",
        "window": "last_month",
        "scope": {"country_code": "US"},
        "breakdown": "failure_reason",
    },
    "EV-020": {
        "metric": "method_paid_order_share",
        "window": "last_month",
        "scope": {"country_code": "GB"},
        "method": "pay_later",
    },
    "EV-021": {
        "metric": "captured_gmv",
        "window": "july_2026",
        "currency": "INR",
        "scope": {"country_code": "IN"},
        "breakdown": "method",
    },
    "EV-022": {"metric": "attach_rate", "window": "last_month", "scope": {"city_name": "Madurai"}},
    "EV-023": {"metric": "captured_gmv", "window": "fy2026_q1", "currency": "USD"},
    "EV-024": {
        "metric": "multi_attempt_orders",
        "window": "last_month",
        "scope": {"country_code": "GB"},
    },
    "EV-025": {
        "metric": "refunded_amount",
        "window": "july_2026",
        "currency": "AED",
        "scope": {"country_code": "AE"},
        "breakdown": "reason",
    },
    "EV-026": {
        "metric": "success_rate_order",
        "window": "last_week",
        "scope": TN,
        "method": "upi",
        "breakdown": "city_name",
    },
    "EV-027": {
        "metric": "net_revenue",
        "window": "july_2026",
        "currency": "USD",
        "breakdown": "country_code",
    },
    "EV-028": {
        "metric": "refund_rate",
        "window": "last_month",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
        "breakdown": "showroom_name",
    },
    "EV-029": {
        "metric": "items_per_order",
        "window": "last_month",
        "scope": {"country_code": "SG"},
    },
    "EV-030": {
        "metric": "orders_count",
        "window": "last_month",
        "scope": {"country_code": "IN"},
        "breakdown": "channel",
    },
    "EV-049": {
        "metric": "pending_refund_count",
        "window": "pending_as_at_as_of",
        "breakdown": "country_code",
    },
    "EV-051": {
        "metric": "captured_gmv",
        "window": "july_2026",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
        "breakdown": "acquiring_bank",
    },
    "EV-052": {
        "metric": "captured_gmv",
        "window": "july_2026",
        "currency": "INR",
        "scope": {"city_name": "Coimbatore"},
    },
    "EV-053": {"metric": "units_sold", "window": "july_2026", "scope": {"country_code": "US"}},
    "EV-054": {"metric": "attempts_count", "window": "last_week", "scope": TN},
    "EV-055": {"metric": "unsettled_amount", "window": "july_2026", "currency": "USD"},
    "EV-056": {"metric": "settlement_lag", "window": "august_2026", "breakdown": "country_code"},
    "EV-057": {
        "metric": "duplicate_capture_count",
        "window": "last_8_weeks",
        "scope": {"country_code": "IN"},
        "breakdown": "weekly",
    },
    "EV-058": {
        "metric": "duplicate_capture_share",
        "window": "august_2026",
        "scope": {"country_code": "IN"},
    },
    "EV-059": {
        "metric": "emi_share",
        "window": "july_2026",
        "currency": "USD",
        "breakdown": "country_code",
    },
    "EV-060": {
        "metric": "average_order_value",
        "window": "last_month",
        "currency": "INR",
        "scope": TN,
        "method": "emi",
    },
    "EV-061": {"metric": "orders_count", "window": "yesterday", "breakdown": "country_code"},
    "EV-062": {
        "metric": "captured_gmv",
        "window": "yesterday",
        "currency": "INR",
        "scope": CHENNAI,
    },
    "EV-063": {
        "metric": "captured_gmv",
        "window": "this_month_to_date",
        "currency": "INR",
        "scope": {"country_code": "IN"},
        "breakdown": "compare",
    },
    "EV-064": {
        "metric": "refund_rate",
        "window": "last_week",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
        "breakdown": "compare",
    },
    "EV-065": {"metric": "units_sold", "window": "last_month", "breakdown": "compare:country_code"},
    "EV-066": {
        "metric": "success_rate_order",
        "window": "last_7_days",
        "scope": {"country_code": "GB"},
        "breakdown": "daily",
    },
    "EV-067": {
        "metric": "refunded_amount",
        "window": "last_8_weeks",
        "currency": "AED",
        "scope": {"country_code": "AE"},
        "breakdown": "weekly",
    },
    "EV-068": {
        "metric": "refund_rate",
        "window": "last_month",
        "currency": "INR",
        "scope": {"country_code": "IN"},
        "method": "emi",
        "breakdown": "issuing_bank",
    },
    "EV-069": {
        "metric": "settlement_lag",
        "window": "july_2026",
        "scope": {"country_code": "GB"},
        "method": "card",
        "breakdown": "card_network",
    },
    "EV-070": {"metric": "units_sold", "window": "last_month", "scope": TN},
    "EV-071": {
        "metric": "average_order_value",
        "window": "last_week",
        "currency": "INR",
        "scope": TN,
    },
    "EV-072": {
        "metric": "attach_rate",
        "window": "last_month",
        "scope": {"country_code": "MY"},
        "breakdown": "channel",
    },
    "EV-073": {
        "metric": "success_rate_attempt",
        "window": "july_2026",
        "scope": {"country_code": "GB"},
    },
    "EV-074": {
        "metric": "captured_gmv",
        "window": "last_month",
        "currency": "SGD",
        "scope": {"country_code": "SG"},
        "breakdown": "storage_gb",
        "breakdown_via": "handset",
    },
    "EV-075": {
        "metric": "units_sold",
        "window": "last_month",
        "scope": TN,
        "breakdown": "colour",
        "breakdown_via": "line",
    },
    "EV-076": {
        "metric": "net_revenue",
        "window": "july_2026",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
        "method": "pay_later",
    },
    "EV-077": {
        "metric": "orders_count",
        "window": "last_week",
        "scope": {"country_code": "GB"},
        "breakdown": "showroom_name",
    },
    "EV-078": {"metric": "success_rate_order", "window": "last_month", "breakdown": "country_code"},
    "EV-079": {
        "metric": "refunded_amount",
        "window": "last_month",
        "currency": "INR",
        "scope": TN,
        "breakdown": "city_name",
    },
    "EV-080": {"metric": "order_to_first_attempt_seconds", "window": "last_month"},
    "EV-100": {
        "metric": "pending_refund_value",
        "window": "pending_as_at_as_of",
        "currency": "USD",
    },
    "EV-101": {
        "metric": "captured_gmv",
        "window": "last_month",
        "currency": "SGD",
        "scope": {"country_code": "SG"},
        "breakdown": "model_name",
        "breakdown_via": "handset",
    },
    "EV-102": {
        "metric": "net_revenue",
        "window": "july_2026",
        "currency": "AED",
        "scope": {"country_code": "AE"},
        "breakdown": "model_name",
        "breakdown_via": "handset",
    },
    "EV-104": {
        "metric": "refunded_amount",
        "window": "july_2026",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
        "breakdown": "model_name",
        "breakdown_via": "handset",
    },
    "EV-105": {
        "metric": "average_order_value",
        "window": "last_month",
        "currency": "MYR",
        "scope": {"country_code": "MY"},
        "breakdown": "model_name",
        "breakdown_via": "handset",
    },
    "EV-106": {
        "metric": "captured_gmv",
        "window": "last_month",
        "currency": "USD",
        "breakdown": "country_code",
    },
    "EV-107": {
        "metric": "orders_count",
        "window": "last_week",
        "scope": {"country_code": "GB"},
        "breakdown": "city_name",
    },
    "EV-108": {
        "metric": "captured_gmv",
        "window": "july_2026",
        "currency": "USD",
        "scope": {"country_code": "US"},
    },
    "EV-109": {
        "metric": "success_rate_order",
        "window": "last_month",
        "scope": {"country_code": "MY"},
        "breakdown": "method",
    },
    "EV-110": {
        "metric": "units_sold",
        "window": "july_2026",
        "scope": {"country_code": "SG"},
        "breakdown": "channel",
    },
    "EV-111": {
        "metric": "refund_rate",
        "window": "last_month",
        "currency": "USD",
        "scope": {"country_code": "US"},
    },
    "EV-112": {
        "metric": "captured_gmv",
        "window": "last_month",
        "currency": "INR",
        "scope": {"city_name": "Coimbatore"},
        "breakdown": "showroom_name",
    },
    "EV-113": {
        "metric": "settlement_lag",
        "window": "july_2026",
        "scope": {"country_code": "SG"},
        "method": "wallet",
    },
    "EV-114": {
        "metric": "success_rate_order",
        "window": "last_month",
        "scope": {"country_code": "GB"},
        "method": "pay_later",
        "breakdown": "issuing_bank",
    },
    "EV-115": {
        "metric": "net_revenue",
        "window": "july_2026",
        "currency": "INR",
        "scope": {"country_code": "IN"},
        "breakdown": "acquiring_bank",
    },
    "EV-116": {
        "metric": "units_sold",
        "window": "last_month",
        "scope": TN,
        "accessories_only": True,
    },
    "EV-117": {
        "metric": "emi_share",
        "window": "last_month",
        "currency": "INR",
        "scope": {"country_code": "IN"},
        "breakdown": "emi_tenure_months",
    },
    "EV-118": {
        "metric": "captured_gmv",
        "window": "this_week_to_date",
        "currency": "GBP",
        "scope": {"country_code": "GB"},
        "breakdown": "compare",
    },
    "EV-119": {
        "metric": "refund_rate",
        "window": "this_month_to_date",
        "currency": "USD",
        "breakdown": "compare:country_code",
    },
    "EV-120": {
        "metric": "success_rate_order",
        "window": "last_7_days",
        "scope": CHENNAI,
        "method": "upi",
        "breakdown": "daily",
    },
    "EV-121": {
        "metric": "settlement_lag",
        "window": "last_8_weeks",
        "scope": {"country_code": "AE"},
        "breakdown": "weekly",
    },
    "EV-122": {
        "metric": "average_order_value",
        "window": "last_month",
        "currency": "SGD",
        "scope": {"country_code": "SG"},
        "method": "card",
        "breakdown": "card_network",
    },
    "EV-123": {
        "metric": "orders_count",
        "window": "last_month",
        "scope": {"country_code": "GB"},
        "status": "abandoned",
    },
    "EV-124": {
        "metric": "failure_rate",
        "window": "last_month",
        "scope": {"country_code": "IN"},
        "breakdown": "issuing_bank",
    },
    "EV-125": {
        "metric": "captured_gmv",
        "window": "this_month_to_date",
        "currency": "INR",
        "scope": TN,
    },
    "EV-126": {
        "metric": "units_sold",
        "window": "july_2026",
        "scope": {"country_code": "GB"},
        "handsets_only": True,
        "breakdown": "model_name",
        "breakdown_via": "line",
    },
    "EV-127": {
        "metric": "captured_gmv",
        "window": "fy2027_q1",
        "currency": "USD",
        "breakdown": "country_code",
    },
    "EV-128": {
        "metric": "attach_rate",
        "window": "this_month_to_date",
        "scope": {"country_code": "GB"},
        "breakdown": "compare",
    },
    "EV-129": {
        "metric": "net_revenue",
        "window": "this_month_to_date",
        "currency": "SGD",
        "scope": {"country_code": "SG"},
        "breakdown": "compare",
    },
    "EV-130": {
        "metric": "failure_rate_by_reason",
        "window": "last_week",
        "scope": TN,
        "method": "upi",
        "breakdown": "failure_reason",
    },
    "EV-149": {
        "metric": "pending_refund_value",
        "window": "july_2026",
        "scope": CHENNAI,
        "currency": "INR",
        "breakdown": "refund_id",
    },
    "EV-150": {"metric": "refund_age_days", "window": "pending_as_at_as_of"},
}
